id = "typos"
name = "Typos"
authors = ["d1y <chenhonzhou@gmail.com>"]
description = "Source code spell checker for Visual Studio Code, Neovim and other LSP clients"
repository = "https://github.com/d1y/typos-zed"
schema_version = 1
version = "0.0.1"

[language_servers.typos]
name = "typos-lsp"
code_action_kinds = ["", "quickfix"]
languages = [
  "TypeScript",
  "JavaScript",
  "Vue.js",
  "Go",
  "Go Mod",
  "Go Work",
  "Shell Script",
  "HTML",
  "Scheme",
  "Lua",
  "Dart",
  "Zig",
  "C",
  "C++",
  "CSS",
  "JSON",
  "Markdown",
  "Ruby",
  "Rust",
  "YAML",
  "TOML",
  "Git Commit",
  "Git Ignore",
  "Plain Text",
  "Unknow",
]